baseURL: "https://mlbj.github.io/"
languageCode: "en-us"
title: "Mauro Brandão"
theme: "PaperMod"

params:
  disableThemeToggle: true
  defaultTheme: light
  hideFooter: true

menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Archive"
      url: "/archives/"
      weight: 1

